### ISSUE TITLE
KeyError for references

### ISSUE THREAD

**Issue by tgpfeiffer** [FebruaryBreeze/json-schema-to-class#8]
I am trying to process https://raw.githubusercontent.com/docker/compose/master/compose/config/config_schema_v2.4.json with this library, but it fails with

```
Traceback (most recent call last):
  File "/home/user/.envs/test/bin/json-schema-to-class", line 8, in <module>
    sys.exit(main())
  File "/home/user/.envs/test/lib/python3.7/site-packages/json_schema_to_class.py", line 262, in main
    print(generate_code(arguments.schema_path))
  File "/home/user/.envs/test/lib/python3.7/site-packages/json_schema_to_class.py", line 229, in generate_code
    parser.parse(schema=schema)
  File "/home/user/.envs/test/lib/python3.7/site-packages/json_schema_to_class.py", line 204, in parse
    item = self.parse_definition(name=name, schema=definition)
  File "/home/user/.envs/test/lib/python3.7/site-packages/json_schema_to_class.py", line 184, in parse_definition
    return self.parse_object(name=name, schema=schema)
  File "/home/user/.envs/test/lib/python3.7/site-packages/json_schema_to_class.py", line 170, in parse_object
    item = self.parse_definition(name=name, schema=definition)
  File "/home/user/.envs/test/lib/python3.7/site-packages/json_schema_to_class.py", line 184, in parse_definition
    return self.parse_object(name=name, schema=schema)
  File "/home/user/.envs/test/lib/python3.7/site-packages/json_schema_to_class.py", line 170, in parse_object
    item = self.parse_definition(name=name, schema=definition)
  File "/home/user/.envs/test/lib/python3.7/site-packages/json_schema_to_class.py", line 186, in parse_definition
    return self.parse_array(name=name, schema=schema)
  File "/home/user/.envs/test/lib/python3.7/site-packages/json_schema_to_class.py", line 175, in parse_array
    items = self.parse_definition('items', schema['items'])
  File "/home/user/.envs/test/lib/python3.7/site-packages/json_schema_to_class.py", line 198, in parse_definition
    return Definition(name=name, class_type=self.definitions[path].name, path=path)
KeyError: '#/definitions/blkio_limit'
```

Does anyone have an idea why that is?

**Comment by SF-Zhou** [comment]
Well, it's a known bug and I will fix it as soon as possible.

**Comment by SF-Zhou** [comment]
The definitions key error is fixed, but there is still no support for the keyword `oneOf`. I may add this feature when I have time.
