### ISSUE TITLE
ValueError - converting str

### ISSUE THREAD

**Issue by irwincong** [FebruaryBreeze/json-schema-to-class#9]
Using https://www.first.org/cvss/cvss-v3.0.json I got the below error.  I thought this strange, since https://json-schema.org/understanding-json-schema/reference/string.html said that it should just convert to a Python `str` object.  I haven't looked at this repo's code to figure out why.

```
json-schema-to-class -o cvss-v3.0.py ./src/known-vulns/nist/cvss-v3.0.json 
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/test/bin/json-schema-to-class", line 11, in <module>
    load_entry_point('json-schema-to-class==0.2.2', 'console_scripts', 'json-schema-to-class')()
  File "/home/vagrant/.virtualenvs/test/lib/python3.6/site-packages/json_schema_to_class.py", line 265, in main
    generate_file(Path(arguments.schema_path), Path(arguments.output_path))
  File "/home/vagrant/.virtualenvs/test/lib/python3.6/site-packages/json_schema_to_class.py", line 235, in generate_file
    lazy_write.write(output_path, generate_code(schema_path))
  File "/home/vagrant/.virtualenvs/test/lib/python3.6/site-packages/json_schema_to_class.py", line 231, in generate_code
    return parser.generate()
  File "/home/vagrant/.virtualenvs/test/lib/python3.6/site-packages/json_schema_to_class.py", line 215, in generate
    result.append(definition.to_class_code(level=0))
  File "/home/vagrant/.virtualenvs/test/lib/python3.6/site-packages/json_schema_to_class.py", line 74, in to_class_code
    raise ValueError(f'Cannot convert [{self.type_name()}] to class!')
ValueError: Cannot convert [str] to class!
```

In all honesty, I wanted to use this to process the "top-level" json-schema at https://csrc.nist.gov/schema/nvd/feed/1.1/nvd_cve_feed_json_1.1.schema, but (1) I didn't know how to tie multiple schemas together to use with this tool and (2) I thought it best to start from the one schema that did not have any external dependencies.

**Comment by SF-Zhou** [comment]
Currently only a subset of JSON Schema specification is supported. In your schema file, the definition of basic type is not supported right now because it cannot be converted to a Python class directly. The definition of object type is OK, like https://github.com/FebruaryBreeze/line-chain/blob/master/line_chain/schema/line_chain_config.json#L11.
```json
{
    "definitions": {
        "attackVectorType": {
            "type": "string",
            "enum": [ "NETWORK", "ADJACENT_NETWORK", "LOCAL", "PHYSICAL" ]
        }
    }
}
```
I don’t have enough time to maintain it. However the core code is very short. PR is welcome :D
